#ifndef ASFEM_NONLINEARSOLVERTYPE_H
#define ASFEM_NONLINEARSOLVERTYPE_H

enum class NonLinearSolverType
{
    LINEAR,
    NEWTONRAPHSON,
    MODIFIEDNEWTON,
    NEWTONWITHLINESEARCH,
    NEWTONWITHBISECTIONLINESEARCH,
    NEWTONWITHREGULARFALSILINESEARCH,
    BFGS
};

#endif // ASFEM_NONLINEARSOLVERTYPE_H