#ifndef ASFEM_MATERIALTYPE_H
#define ASFEM_MATERIALTYPE_H

enum class MaterialType
{
    NULLMATE,
    CONSTPOISSONMATE,
    NONLINEARPOISSONMATE,
    ANISOPOISSONMATE,
    CONSTDIFFUSIONMATE,
    NONLINEARDIFFUSIONMATE,
    GENERALWAVEMATE,
    ANISODIFFUSIONMATE,
    LINEARELASTICMATE,
    NEOHOOKEANMATE,
    CAHNHILLIARDMATE,
    FINITESTRAINMATE,
    STVENANTMATE,
    MOONEYRIVLINMATE,
    ELASTICTHERMALMEHCANICSMATE,
    NEOHOOKEANTHERMALMECHANICSMATE,
    NEOHOOKEANCAHNHILLIARDMATE,
    LINEARELASTICPHASEFIELDFRACTUREMATE,
    MODIFYELASTICFRACTUREMATE,
    USER1MATE,
    USER2MATE,
    USER3MATE,
    USER4MATE,
    USER5MATE,
    USER6MATE,
    USER7MATE,
    USER8MATE,
    USER9MATE,
    USER10MATE
};

#endif // ASFEM_MATERIALTYPE_H