//****************************************************************
//* This file is part of the AsFem framework
//* A Simple Finite Element Method program (AsFem)
//* All rights reserved, Yang Bai/M3 Group@CopyRight 2020-present
//* https://github.com/M3Group/AsFem
//* Licensed under GNU GPLv3, please see LICENSE for details
//* https://www.gnu.org/licenses/gpl-3.0.en.html
//****************************************************************
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//+++ Author : Yang Bai
//+++ Date   : 2022.11.18
//+++ Purpose: Implement the gmsh2 file import function.
//+++          This mesh file must be the *.gmsh2, which should be
//+++          generated by netgen
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#pragma once

#include "Mesh/MeshFileImporterBase.h"
#include "Mesh/MshFileUtils.h"

/**
 * This class implements the msh file (version-2) import function.
 */
class Gmsh2FileImporter:public MeshFileImporterBase{
protected:
    /**
     * This function implement the mesh file import.
     * @param filename the mesh file's string name
     * @param t_meshdata the mesh data structure
     */
    virtual bool importMeshFile(const string &filename,MeshData &t_meshdata) override;

private:
    /**
     * get the maximum dimension of the bulk mesh from msh file
     * @param filename the msh file name
     */
    int getMaxMeshDim(const string &filename)const;

};